todoapp/urls.py
from django.urls import path
from . import views

# refactor/src:  https://youtu.be/CA5duCGDSUE
# src: https://docs.djangoproject.com/en/4.2/howto/static-files/
from django.conf import settings
from django.conf.urls.static import static


app_name = 'todoapp' # giving this URLs.py an app name means that
                     # refering to it in html needs to precede it.
"""
w/o app_name:
    <form action="{% url 'edit_django_name' todoitem.id %}">
w/ app name:    
app_name = 'todoapp'
    <form action="{% url 'todoapp:edit_django_name' todoitem.id %}">
    
"""

urlpatterns = [
    path("", views.index_todoapp, name="to_do_django_name"),
    path("home",views.index_todoapp, name="to_do_django_name"),
    path("edit/<int:task_id>/", views.editTask, name="edit_django_name"),
    path("delete/<int:task_id>/", views.deleteTask, name="delete_django_name"),
   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # this is a helper function
# and only works in debug mode and should be discarded during production
# src: https://docs.djangoproject.com/en/4.2/howto/static-files/
# 1 implementation of this and the above x2 Import statements

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

#from todoapp.views import index_todoapp


# refactor/src:  https://youtu.be/CA5duCGDSUE
# src: https://docs.djangoproject.com/en/4.2/howto/static-files/
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include("todoapp.urls")),
    path('admin/', admin.site.urls), # works with admin too  , i.e. no
    #path('home/',index_todoapp, name='homepage'),
    #path('/',include("todologin.urls")),
    #path('accounts/', include("todologin.urls")),
    path('',include('django.contrib.auth.urls')), #https://docs.djangoproject.com/en/4.2/topics/auth/default/#using-the-views
    # accounts/login/ [name='login']
    # accounts/logout/ [name='logout']
    # accounts/password_change/ [name='password_change']
    # accounts/password_change/done/ [name='password_change_done']
    # accounts/password_reset/ [name='password_reset']
    # accounts/password_reset/done/ [name='password_reset_done']
    # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # accounts/reset/done/ [name='password_reset_complete']
    #                             
    path('sign-up',include("todologin.urls")),
    #path('signup/',include("todoapp.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # this is a helper function
# and only works in debug mode and should be discarded during production
# src: https://docs.djangoproject.com/en/4.2/howto/static-files/
#  2 implementation of this and the above x2 Import statements
""" 
src: https://docs.djangoproject.com/en/4.2/topics/auth/default/#using-the-views
included with:path('',include('django.contrib.auth.urls'))

>>>
accounts/login/ [name='login']
accounts/logout/ [name='logout']
accounts/password_change/ [name='password_change']
accounts/password_change/done/ [name='password_change_done']
accounts/password_reset/ [name='password_reset']
accounts/password_reset/done/ [name='password_reset_done']
accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/reset/done/ [name='password_reset_complete']


"""

todoapp/models.py
from django.conf import settings
from django.db import models
from django.apps import apps # https://stackoverflow.com/a/43847288


# Create your models here.
class ToDoItem(models.Model):
    #task_author = models.ForeignKey('todologin.DashboardUser',on_delete=models.CASCADE) #https://stackoverflow.com/a/43847288
    #https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#referencing-the-user-model
    task_author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE) # https://stackoverflow.com/a/40954392
    task_description = models.CharField(max_length=50)
    task_complete = models.BooleanField(default=False)
    task_created = models.DateTimeField(auto_now_add=True)
    task_is_private = models.BooleanField(default=False)
    
    
    
    def __str__(self):
        return self.task_description
    

todoapp/forms.py
from django import forms
from django.forms import ModelForm, Textarea, TextInput, CheckboxInput

from .models import ToDoItem

INPUT_CLASSES   = 'w-full border mt-4 mb-6 px-2 py-4'
EDIT_CLASS      = 'auto w-full bg-stone-50 mt-6 mb-8 py-4 pt-6 pr-3 pb-16 pl-3 rounded'
EDIT_BOX        = 'w-8 align-middle m-3 rounded'

class TaskForm(ModelForm):
    class Meta:
        model = ToDoItem # The model we're working on 
        fields = ('task_description',)


        widgets = {
            'task_description': TextInput(attrs={'placeholder':'Add a new task ...',
                                                 'class':INPUT_CLASSES, })  
        }



class EditForm(ModelForm):
    class Meta:
        model = ToDoItem
        fields = ('task_description', 'task_complete', 'task_is_private')
        
        widgets = {
            'task_description': TextInput(attrs={'class':EDIT_CLASS}),
            'task_complete': CheckboxInput(attrs={}),
            'task_is_private': CheckboxInput(attrs={}),
            
        }
        

todoapp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import authenticate
from django.contrib import messages

from django.contrib.auth.decorators import login_required

import datetime

from django.db.models import Q
from todologin.models import DashboardUser
from .models import ToDoItem

from .forms import TaskForm, EditForm

from django.apps import apps

PREVIEW_TEXT = "PRIVATE TASK"

# Return either admin + public tasks OR admin + user specific/logged in tasks
def user_todolist(request):
    # we pass the user
    # we filter 
    # we want to separate what is passed from the view, i.e. don't filter inside the 
    # view because, then you're sending the entire data set .. SO
    # filter before hand, HOWEVER, i also want to SEE the presence of a filtered
    # to do (i.e. hinting at tasks that others have. ) so each non user task should
    # default to a dummy secret task. 
    # so, we cycle through each element, and if it is NOT the user
    # we replace it with a dummy task - i.e. 'Premium sneak preview'

    try:
        if ToDoItem.objects.all():
            pass
    except:
        return HttpResponseRedirect('/')
    all_tasks = ToDoItem.objects.all()

    returned_list = []

    if request.user.is_authenticated:
        tasks_all = ToDoItem.objects.all()
        user_admin = DashboardUser.objects.get(username="admin")
        tasks_admin_and_user = []
        # capture admin + logged in user tasks (i.e. private tasks)
        for task in tasks_all:
            if (task.task_author == request.user): # or (task.task_author == user_admin):
                tasks_admin_and_user.append(task)
            elif(task.task_author == user_admin):
                # user task
                if(task.task_is_private != True):
                    # public task - everyone sees
                    tasks_admin_and_user.append(task)
                else:
                    # private task - only admin sees
                    user_admin_dummy = DashboardUser.objects.get(username="admin")
                    
                    private_task = task
                    private_task.task_description=PREVIEW_TEXT
                    private_task.task_complete= False
                    private_task.task_is_private=True
                    
                    tasks_admin_and_user.append(private_task)
            elif (task.task_is_private != True):
                tasks_admin_and_user.append(task) 
            else:
                user_admin_dummy = DashboardUser.objects.get(username="admin")
                
                private_task = task
                private_task.task_description=PREVIEW_TEXT
                private_task.task_complete= False
                private_task.task_is_private=True
                
                tasks_admin_and_user.append(private_task)
        returned_list = tasks_admin_and_user      
    else:
        # capture admin + public tasks
        tasks_all = ToDoItem.objects.all()
        tasks_for_non_accounts = []
        for task in tasks_all:
            if task.task_is_private:
                user_admin_dummy = DashboardUser.objects.get(username="admin")
                # dummy storage
                private_task = task
                private_task.task_description=PREVIEW_TEXT
                private_task.task_complete= False
                private_task.task_is_private=True
                tasks_for_non_accounts.append(private_task)
            else:
                tasks_for_non_accounts.append(task)
        returned_list = tasks_for_non_accounts    
    context = {
        "returned_list" : returned_list,
    }
    return context

def index_todoapp(request):
    # Main page
    # Display a list of tasks, some hidden (if the task is hidden)
    # and the current user is not the task owner, allow anyone
    # to add/edit/delete shared tasks, make unique/their own
    # tasks and edit/delete/add private tasks
    if request.method == "POST":
        if 'submit' in request.POST:
            # Create a form instance and populate it with data from the request:
            form_view = TaskForm(request.POST) # https://docs.djangoproject.com/en/4.2/topics/forms/#:~:text=if%20request.method%20%3D%3D%20%22POST%22%3A
            # Is this form filled with valid information? 
            if form_view.is_valid():    
                if request.user.is_authenticated:
                    # SOMEONE IS LOGGED IN
                    task = form_view.save(commit=False)
                    task_author = request.user
                    task.task_author = task_author
                    task.save()

                    tasks_all = ToDoItem.objects.all()
                    user_admin = DashboardUser.objects.get(username="admin")
    
                    tasks_admin_and_user = []
                    
                    for task in tasks_all:
                        """ DEBUG:
                        if (task.task_author == user_admin) :
                            print("user_admin entry found at for task " + task.task_description )
                        if (task.task_author == request.user) :
                            print(" a task for this user: " + request.user.username + ", has been found: " + task.task_description)
                        """
                        if(task.task_author == user_admin) or (task.task_author == request.user):
                            tasks_admin_and_user.append(task)
                    form_view = TaskForm()
                    return HttpResponseRedirect('/')
                else:
                    if DashboardUser.objects.filter(username='admin').exists():
                        task = form_view.save(commit=False)
                        adminUser = DashboardUser.objects.get(username='admin')
                        if adminUser:
                            task.task_author = adminUser
                            task.save()
                            form_view = TaskForm()
                            return HttpResponseRedirect('/')
                    else:
                                      
                        #IMPORTANT TO NOTE: IF ADMIN IS ALREADY A USER THIS DOESNT CREATE ONE
                        # Create a new admin
                        admin_new = DashboardUser.objects.create_user(username='admin', email='admin@admin.com',password='simplepass123')
                     
                        task = form_view.save(commit=False)
                        adminUser = DashboardUser.objects.get(username='admin')
                        task.task_author = adminUser
                        task.save()
                        form_view = TaskForm()
                        return HttpResponseRedirect('/')
        else:
            form_view = TaskForm
    else:
        # A redirect comes here because the method is a GET; i.e. the first time or non-form POST request
        form_view = TaskForm 

    todolist = ToDoItem.objects.order_by('id')

    context = user_todolist(request) 
    todolist = context['returned_list']
    
    current_user = request.user
    
    """
    # logic for the background profile pics
                        <!-- see if the task is private -->
                        <!-- get the user who created the task -->
                        
                        <!-- see if the user has a profile pic -->

                        <!-- if the user has a profile pic, set it to background -->
                        <!-- if no user profile pic, set to defult background -->
       choosing to do logic here and not in html because this is the CONTROLLER
       the trick is, the tasks, do not store user info, and we want to be
       able to change task owners, so we are only pointing to the user,
       not to the image, of the user, which is in the user data SO
       we need to create a parallel list for each task and copy in the
       image address for each user tied to each.
       Got this feature to work, but ultimately excised it out, due to
       need for multiple divs etc and too cluttered an UI          
    """
    #task_user_images = []
    
    task_abs_path_images=[]
    beginfix = '/media/'
    task_str_paths=[]
    
    
    for task_in in todolist:
        
        profile_pic_flag = False
        # Get the user who created the task
        task_author_ = task_in.task_author
        
        # Test if the task user has a profile pic
        # No need we have now defaulted
        
        if task_in.task_is_private and current_user != task_author_:
            # Task Private                          = YES; 
            # Task owner IS the browser user        = NO
            # Dummy image
            # THIS is the special case where we show dummy
            # BUT instead, lets just add the admin image.
          
            # IMPORTANT TO NOTE: IF ADMIN IS ALREADY A USER THIS DOESNT CREATE ONE
            # Create a new admin
            if DashboardUser.objects.filter(username='admin').exists():
                
                admin_user = DashboardUser.objects.get(username='admin')
                admin_profile_pic = admin_user.user_image
               
            else:
                admin_new = DashboardUser.objects.create_user(username='admin', email='admin@admin.com',password='simplepass123',user_image='profile_pics/no_prof_pic.PNG')
                admin_user = DashboardUser.objects.get(username='admin')
                admin_profile_pic = admin_user.user_image
            

            #task_user_images.append({'image': admin_profile_pic, 'idkey': task_in.pk })
            temp = beginfix + str(admin_profile_pic) 
            task_abs_path_images.append({'image': temp, 'idkey': task_in.pk   })
        elif task_in.task_is_private and current_user == task_author_:
            # Task Private                          = YES; 

todoapp/templates/todoapp/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <style>        </style>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

        <title> {% block title %} {% endblock %} | Web App </title>

        {% block headlinks %} 
        {% endblock %}

        {% load crispy_forms_tags %}
        {% load static %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    
    </head>
    <body class="bg-[#f6f4fb] pt-10 pb-10 mb-10"   style="background-image: url('{% static 'todolist/moneis.png' %}'); " >
    <div class="">
      <div class="text-black">TEST BUILD</div>   
        <div class="mx-auto max-w-prose bg-[#664798] shadow-[0px_22px_70px_4px_rgba(0,0,0,0.56)] rounded-xl">
   
            <div class="flex flex-row py-2 " >
                <div class= "flex basis-3/5 items-center justify-center text-[#F5F5F5] text-4xl "><a href="/"><strong>Task WebApp</strong></a></div>
                <div class= "flex basis-2/5 items-center justify-end pr-3">
                    <div class="flex mt-2">
                        
                            {% if user.is_authenticated %}
                            
                                <form action="/logout/">
                                    <button type="submit"  class="bg-[#087E8B] px-3 py-2 text-[#F5F5F5] rounded-2xl">Log Out</button>
                                </form> 

                            {% else %}

                                <form action="/login/"> 
                                    <button type="submit"  class="bg-[#087E8B] px-4 py-2 mr-6 text-[#F5F5F5] rounded-2xl">Log In</button>
                                </form>

                                <form action="/sign-up"> 
                                    <button type="submit"  class="bg-[#087E8B] px-3 py-2 text-[#F5F5F5] rounded-2xl">Sign Up</button>
                                </form>

                            {% endif %}
                    </div>
                </div>
            </div>

        
            <div class="flex justify-center h-10 p-1 pt-2 text-[#F5F5F5]">
                {% if user.is_authenticated %}
                        {% if user.username == "DarthVader" %}
                            <span class="text-xs">Greetings <strong>Lord Vader</strong>,</span>
                        {% else %}
                            <span class="text-xs">Greetings {{ user.username }},</span>
                        {% endif %}
                {% endif %}
            </div>


        {% block content %}
            

        {% endblock %}
        </div>

        <p class="mt-4 text-[#2b2c2c] text-center text-xs">Hello there, looking for the <a href="/admin/">admin site</a>?</p>

    </div>




    <div class="mx-auto max-w-prose bg-[#664798] border h-100 p-2 mt-10 text-[#F5F5F5] text-center rounded" >
        <h1>Contact Us</h1>
        <div class="">
            Task WebApp &copy; 2023
        <div>
    </div>
    </body>

</html>

todoapp/templates/todoapp/delete.html
{% extends 'todoapp/base.html' %}
{% block title %}Delete Task{% endblock %}


{% block headlinks %} 

<style>



</style>
{% endblock %}
{% block content %}



    <form action="" method="post" class="mx-auto bg-slate-200 border px-5 py-2 pt-5 rounded-xl">

        {% csrf_token %}
        <div class="text-neutral-800 text-center text-2xl" > Delete Task</div>

        <div class="grid grid-rows-1 grid-flow-col gap-1 "> 
            <div class="row-start-1 row-span-1 ">
                <div class="pt-6 text-neutral-800 text-center text-xs" > 
                    Are you sure you want to delete the following task: 
                    <div class="bg-sky-50 mt-6 mb-6 pt-10 pb-16"> 
                        <p style="font-style:italic " class="text-lg">
                        {{ taskDescription }}
                        </p>
                    </div>
                </div>
            </div>
        </div>


        <div class="flex ">
            <input type="submit" name="submit-deletion" value="Yes" class="m-auto bg-red-600 px-10 py-2 text-white text-2xl rounded">
        </div>
 
        
        <div class="flex pt-2 pb-2">
            <input type="submit" name="cancel-deletion" value="Cancel" class="m-auto bg-[#0a97bb] px-4 py-2 text-white text-2xl rounded">
        </div>

 


    </form>

{% endblock %}

todoapp/templates/todoapp/edit.html
{% extends 'todoapp/base.html' %}
{% block title %}Edit Task {% endblock %}


{% block headlinks %} 

<style>




</style>
{% endblock %}
{% block content %}



    <form action="" method="post" class="mx-auto bg-slate-200 border px-3 py-2 pt-5 rounded-xl">

        {% csrf_token %}
        <div class="text-neutral-800 text-center text-2xl" > Update Task</div>
        <div class="pt-6 text-neutral-800 text-center text-xs" > Edit this task in the box below: </div>
        {{ form.task_description }}


        <div class="flex flex-row justify-center gap-5"> 
            <div class="basis-1/2"> <div class="text-neutral-800 text-center text-l" > Task Complete</div></div>
            <div class="basis-1/2"> <div class="text-neutral-800 text-center text-l" > Private Task</div></div>
        </div>


        <div class="flex">
            <div class="m-auto">
                    <div class="">{{ form.task_complete }}</div>    
            </div>
            <div class="m-auto">
                <div class="">{{ form.task_is_private }}</div>    
            </div>
        </div>


        <div class="flex mt-10 mb-6">
            <input type="submit" name="submit" value="Submit" class="m-auto bg-[#0a97bb] px-4 py-2 text-white text-2xl rounded">
        </div>
    </form>

{% endblock %}

todoapp/templates/todoapp/todo_index.html
{% extends 'todoapp/base.html' %}
{% block title %}Task WebApp{% endblock %}
{% block headlinks %} 
    {% load static %}
    
{% endblock %}
{% block content %}

    <div class="mx-auto bg-slate-200 border px-5 py-2  rounded">
        



        <form action="" method="post" class="max-w-lg">
            {% csrf_token %}
            {{ form.task_description }}
            <input type="submit" name="submit" value="Submit" class="w-full bg-[#087E8B] px-5 py-3 mb-3 text-white text-lg rounded">
        </form>


        

        {% if to_do_list %}





            <ul class="mb-10">
                {% for todoitem in to_do_list %}
                <li>
                   <div 


       
                       


                        {% if todoitem.task_is_private != False and todoitem.task_author == current_user %}
                            


                            class="bg-gradient-to-r from-[#D46A55] to-[#B0A8B9] px-3 py-5 mt-2 mb-2 text-white rounded" 

                        {% elif todoitem.task_is_private != False and todoitem.task_author != current_user %}
                            style="filter:brightness(40%);

                            "
                            class="bg-[#442976] px-3 py-5 mt-2 mb-2 text-white rounded" 
                        {% else %}

                            class="bg-gradient-to-r from-[#a28872] to-[#E8D5B5] mt-2 mb-2 px-3 py-5 text-white rounded" 

                        {% endif %}
                        

                        >


                                    <div class="flex flex-row items-center">
                                        <!-- BUTTONS -->
                                        <!-- DEBUG:: {/{current_user}/} -->
                                        <!-- DEBUG:: {/{ todoitem.task_author}/} -->
                                        <!-- NO logic here, display all pics -->
                                        <div class=" px-1 ">

                                            {% if todoitem.task_is_private != False  %}
                                                <!-- The task is Private THANKFULLY the current user is the author! TRUE -->
                                                {% if  todoitem.task_author == current_user %} 
                                                    <form action="{% url 'todoapp:edit_django_name' todoitem.id %}">
                                                        {% csrf_token %}
                                                        <input type="submit" name="edit"   value="Edit"   class="bg-[#087E8B] px-4 py-2 text-white rounded">
                                                    </form>
                                                {% else %}
                                                <form action="">
                                                    {% csrf_token %}
                                                    <input type="submit" name="edit"  disabled value="Edit"   class="bg-[#087E8B] px-4 py-2 text-white rounded">
                                                </form>
                                                {% endif %}
                                            {% elif todoitem.task_is_private != False and todoitem.task_author != current_user %}
                                                <!-- The task is Private AND the current user is not the author! Hidden -->
                                                <!-- might not trigger -->
                                                <form action="" style="filter:brightness(60%)">
                                                    {% csrf_token %}
                                                    <input type="submit" name="edit"   disabled value="Edit"   class="bg-[#087E8B] px-4 py-2 text-white rounded">
                                                </form>
                                            {% else %}
                                                <!-- Public task AND not logged in -->
                                                <form action="{% url 'todoapp:edit_django_name' todoitem.id %}" style="">
                                                    {% csrf_token %}
                                                    <input type="submit" name="edit"   value="Edit"   class="bg-[#087E8B] px-4 py-2 text-white rounded">
                                                </form>
                                            {% endif %}

                                        </div>

                                        <div class="flex-initial">

                                            {% if todoitem.task_is_private != False  %} 
                                                <!-- The task is Private THANKFULLY the current user is the author! TRUE --> 
                                                {% if  todoitem.task_author == current_user %} 
                                                    <form action="{% url 'todoapp:delete_django_name' todoitem.id %}">
                                                        {% csrf_token %}
                                                        <input type="submit" name="Delete" value="Delete" class="bg-[#8D7257] px-3 py-2 text-white rounded">
                                                    </form>
                                                {% else %}
                                                    <!-- The task is Private AND the current user is not the author! Hidden --> 
                                                    <form action="">
                                                        {% csrf_token %}
                                                        <input type="submit" name="Delete" disabled value="Delete" class="bg-[#8D7257] px-3 py-2 text-white rounded">
                                                    </form>
                                                {% endif %}
                                            {% elif todoitem.task_is_private != False and todoitem.task_author != current_user %}
                                                <!-- The task is Private AND the current user is not the author! Hidden --> 
                                                <form action="" style="filter:brightness(60%)">
                                                    {% csrf_token %}
                                                    <input type="submit" name="Delete" disabled value="Delete" class="bg-[#8D7257] px-3 py-2 text-white rounded">
                                                </form>
                                            {% else %}
                                               <!-- Public task AND not logged in --> 
                                                <form action="{% url 'todoapp:delete_django_name' todoitem.id %}" style="">
                                                    {% csrf_token %}
                                                    <input type="submit" name="Delete"  value="Delete" class="bg-[#8D7257] px-3 py-2 text-white rounded">
                                                </form>
                                            {% endif %}
                                        </div>




                                        <!-- LIGHTS -->
                                        <div class="px-2 pb-2">
                                            <div class="  ">
                                                {% if todoitem.task_complete %}
                                                    <div class="bg-lime-400 rounded-full" style="height: 10px; width: 10px; "></div>                                       
                                                {% else %}
                                                    <div class="bg-[#FBD73C] rounded-full" style="height: 10px; width: 10px; "></div>
                                                {% endif %} 
                                            </div>
                                        </div>
                                        <!-- TASK DESCRIPTION -->
                                        <div class="grow text-white text-left">
                                            <div class=" ">  
                                                {% if todoitem.task_complete %}
                                                    <span style= "font-style:italic;color:#110e0b;text-decoration: line-through" > 
                                                {% endif %} 
                                                <strong>{{todoitem.task_description}}</strong>
                                                {% if todoitem.task_complete %} 
                                                    </style>
                                                {% endif %}



                                                <br><div class="mt-2 text-amber-950 text-right text-xs">- Task Owner:{% if todoitem.task_author == current_user%} {{todoitem.task_author}} {% elif todoitem.task_is_private != True %} {{todoitem.task_author}}  {% else %} Private{% endif %} </div>

                                            </div>
                                        </div>
                                    </div>
                        <div>
                    </li>
                {% endfor %}
            </ul>
        
        {% else %}
            <p>~/~ NO TASKS FOUND ~/~</p>
        {% endif %}
    </div>
{% endblock %}